tweag/FawltyDeps

README.md
The GIF shows up nicely on the repo page, but does not render from e.g. our PyPI page: https://pypi.org/project/fawltydeps/
Try to fix that with an absolute URL reference
=> Fix reference to GIF when this document is rendered elsewhere

fawltydeps/main.py, fawltydeps/packages.py, poetry.lock, pyproject.toml, tests/test_local_env.py, tests/test_real_projects.py
This is the most basic building block towards decoupling the venv that FawltyDeps is installed in, from the venv that FawltyDeps is run against. From this we can work towards several goals in future PRs:
- No longer require `pip install fawltydeps` into your project's venv, but instead e.g. `pipx install fawltydeps` to make FD available to all your projects.
- Pass `--venv` as a command line option
- Passing more than one venv
- Auto-detecting and adding venvs under `basepath` (i.e. make `--venv` somewhat similar to `--code` and `--deps`)
- Supporting a first approximation to using PyPI, by downloading/installing packages from PyPI into a temporary venv, and then pointing FD at that venv.
- Changing our `real_projects` tests to no longer have to install/uninstall FD in the experiment's …
=> Teach `packages.LocalPackageLookup` to look at other venvs

fawltydeps/main.py, tests/test_cmdline.py
When checking a project in the (default) summary mode, and no problems
were found, we would still print the following, confusing message to our
users:
For a more verbose report re-run with the `--detailed` option.
Only print that message when there is indeed a preceding report.
Otherwise, when we're checking for undeclared/unused, and no problems
were found, print this friendlier message instead:
No unused or undeclared dependencies detected.
Suggested by @koterpillar in #222.
This fixes #222.
=> main: Write a friendly success message when we find no issues

fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/settings.py, noxfile.py, tests/conftest.py, tests/test_cmdline.py, tests/test_local_env.py, tests/test_real_projects.py, tests/test_settings.py
Depends on #215.
- `packages`: Add `venv_path` argument to `resolve_dependencies()`
- Add `venv` setting and `--venv` command-line option
- `test_real_projects`: Use `--venv` instead of editable install of FD
=> Add `--venv` option to CLI

README.md
To faster detect the failing CI.
If you have any other suggestions on a useful shield, feel free to pick from: https://shields.io
I did a minimal change, because, I do not want to clutter the README with those shields too much. (There are _many_ of them)
=> Add a shield for CI to the top of README

fawltydeps/extract_declared_dependencies.py, noxfile.py, tests/test_extract_declared_dependencies_errors.py, tests/test_extract_declared_dependencies_pyproject_toml.py, tests/test_extract_declared_dependencies_success.py
This should enable @vreuter's rewrite of our requirements.txt parser to avoid creating a temporary copy of each requirements.txt file while parsing it.
We do however need to find a better way to parse our setup.cfg files...
- `test_extract_declared_dependencies_succes`: Harmless test refactoring
- `extract_declared_dependencies`: Refactor API of parser functions
- `test_extract_declared_dependencies_pyproject_toml`: Remove unnecessary `dedent()`
- `extract_declared_dependencies`: Rename parser functions
=> Refactor `extract_declared_dependencies` parser APIs in preparation for #227

fawltydeps/extract_declared_dependencies.py, poetry.lock, pyproject.toml, tests/test_extract_declared_dependencies_success.py
Once https://github.com/nexB/pip-requirements-parser/pull/17 is merged, we could more directly use `pip-requirements-parser` (namely, the `RequirementsParser.from_string` method). Until then, this works around a `NameError` that comes up when using the less common `from_string` method in the `RequirementsFile` class in that project.
=> Leverage existing requirements.txt parsing logic to close #225

README.md
- `README.md`: Rewrite/split the FAQ about unused dependencies.
- `README.md`: Add documentation of `--venv` option.
=> Update `README.md` to document the new `--venv` option

README.md
Thanks for the great project!
With current example I have the following error.
```
➜ fawltydeps                                                                                                                                                                                                                                                                                                                                              nix-shell-env
Traceback (most recent call last):
File "/nix/store/r6d17z5j0ydcvk7dpbbifrxrs6h8w4c7-python3.9-fawltydeps-0.6.1/bin/.fawltydeps-wrapped", line 9, in <module>
sys.exit(main())
File "/nix/store/r6d17z5j0ydcvk7dpbbifrxrs6h8w4c7-python3.9-fawltydeps-0.6.1/lib/python3.9/site-packages/fawltydeps/main.py", line 204, in main
settings = …
```
=> doc: fix configurattion example in pyproject.toml

fawltydeps/main.py, tests/test_cmdline.py
A follow up to #224.
A function in the Analysis class now generates the success message.
This function is static and does not directly rely on the checks (actions) currently activated in an Analysis instance.
I opted for this to avoid creating an Analysis instance in tests just to generate the success message.
=> Adapt success message to the performed checks

fawltydeps/main.py
Since we changed Settings.code from PathOrSpecial to Set[PathOrSpecial],
we now have to be able to represent a set that contains both Path
objects and the "<stdin>" special case. Simply passing this set to
sorted() causes a crash, since Path and str are not orderable (see #233
for details). Instead, sort the set using the _string representation_
of the items in the set.
Fixes #233.
=> main: Fix crash when encoding Settings.code items

tests/test_extract_declared_dependencies_success.py, tests/utils.py
Small cleanup of tests, to finish fixing point:
> gather common helper functions in utils.py and refactor tests cases to use them
of #166.
Remove `dependency_factory` from tests of and use 'deps_factory' from utils in test of extracting dependencies
=> Tests refactor: small fix to deduplicate dependencies factory.

fawltydeps/extract_imports.py, fawltydeps/main.py, fawltydeps/types.py
This refactor makes it easier to test the core functionality of FawltyDeps,
without the necessity to run fawltydeps in a subprocess.
The following things are changed:
- Extract assigning exit code and printing summary message from 'main'.
- Based on @jherland's comments, add arguments to main for: stdin, stdout, list of cmdline args.
Refactor extracting imports accordingly.
- for `--code` using stdin (`-` option), added handling that  checks if the stdin is interactive, and throws error in that case.
=> Tests refactor: Change `main` to explicitly take stdin, stdout for better testability

tests/project_helpers.py, tests/sample_projects/beautifulsoup_and_html5lib/expected.toml, tests/sample_projects/beautifulsoup_and_html5lib/main.py, tests/sample_projects/beautifulsoup_and_html5lib/requirements.txt, tests/sample_projects/beautifulsoup_and_html5lib/requirements.workaround.txt, tests/sample_projects/blog_post_example/expected.toml, tests/sample_projects/file__requirements_undeclared/expected.toml, tests/sample_projects/file__requirements_unused/expected.toml, tests/test_real_projects.py, tests/test_sample_projects.py
This started as a simple wish to add the problem described in issue #246 as a sample project in our test suite.
However, I quickly discovered that our `sample_projects` did not support installing comples dependencies (such as `beautifulsoup4`, much less `beautifulsoup4[html5lib]`. Furthermore, it also did not support running multiple experiments inside a single `sample_project`.
Both of these features are already available in our `real_projects`, so I took this as an opportunity to do some extensive refactoring on `real_projects` and `sample_projects`, and bring these two parts of our test suite as close together as possible:
The common parts are refactored into a new `project_helpers` module (unders `tests/`), and the remaining differences are expressed in the `Experiment` and `*Project` …
=> Develop sample_projects to support multiple experiments and cached venvs

tests/test_cmdline.py
After introducing `--install-deps` in [1443b05](https://github.com/tweag/FawltyDeps/pull/252/commits/1443b05ccd31adca20290f8069b3315d70281668), I had to update the expected json for multiple tests in the cmdline test module.
This could have been avoided if suitable defaults were provided.
Since there are 3 different tests concerned by this, and following @jherland's rule of three, I decided to extract the settings dict into a default customizable representation as has been done in the `test_settings` module. Note that I could not re-use the `make_settings_dict` function from that module as its representation is different from the json representation.
=> Extract default values of settings in cmdline tests

CODE_OF_CONDUCT.md, README.md
Following the example of pandas, in this PR the code of conduct is added. The document is strictly based on https://www.contributor-covenant.org/. The statements are along the lines "do no evil" and are quite universal.
We need to agree on how to handle violations of the code of conduct, especially in `Enforcement` section - supply contact methods. I suggest our tweag emails unless you have some other idea.
=> Add the code of conduct

fawltydeps/packages.py, fawltydeps/settings.py, tests/test_cmdline.py, tests/test_local_env.py, tests/test_packages.py, tests/test_real_projects.py, tests/test_sample_projects.py, tests/utils.py
This does not change current behavior, but does a preliminary
refactoring on the way towards having multiple package-to-import
resolvers as discussed in #256 and associated issues.
Introduce a `BasePackageResolver` abstract base class to define the
interface for package resolvers, and provide, for now, two subclasses:
- `LocalPackageResolver` (renamed from `LocalPackageLookup`)
- `IdentityMapping` (refactored from `resolve_dependencies()`)
Also refactor `resolved_dependencies()` to operate on a list of
`BasePackageResolver` objects: For each dependency name we go through the
list of resolvers until a resolver returns a `Package` object for this
name. We then add this `Package` to the returned mapping.
For now this list of resolvers is hardcoded to exactly two entries, the …
=> package: Introduce a list of package resolvers

noxfile.py
We want to keep track of which tests take the longest to run, both
locally, but especially in CI where we now see very long test runtimes.
Also, add --hypothesis-show-statistics to our "tests" session to print
relevant stats from Hypothesis.
=> noxfile.py: More stats in our test output

fawltydeps/main.py, fawltydeps/settings.py, fawltydeps/utils.py
A small refactor of CLI options order before adding a new CLi option for a user #260 
What has changed:
- `version` function moved to settings module
- all argparse options are moved to settings module
- reorder of options displayed in the help message
- add "Source paths options" as a separate group to easier identify this presumably most common use case.
```
fawltydeps --help
usage: fawltydeps [--check | --check-undeclared | --check-unused | --list-imports | --list-deps] [--summary | --detailed | --json] [--code PATH_OR_STDIN [PATH_OR_STDIN ...]] [--deps PATH [PATH ...]]
[--pyenv PYENV_DIR] [--ignore-undeclared IMPORT_NAME [IMPORT_NAME ...]] [--ignore-unused DEP_NAME [DEP_NAME ...]]
[--deps-parser-choice {requirements.txt,setup.py,setup.cfg,pyproject.toml}] [--config-file CONFIG_FILE] …
```
=> Refactor: reorder CLI options and add "Source paths" group

poetry.lock, pyproject.toml
This supersedes #272, to fix using FawltyDeps with newer versions of Poetry (poetry-core>=1.5.0).
Thanks to @janydoe for submitting #272. This PR rephrases their commit to only include the `poetry.lock`
changes directly associated with the `isort` upgrade, but omitting collateral changes caused by the newer
Poetry version. AFAICS, these collateral changes cause an older Poetry version (e.g. the v1.2.2 version
used by our `shell.nix`) to loop forever when running `poetry lock --no-udpate`.
I also add another commit preventing `isort` from upgrading to v5.12.0, which is the version where isort
drop support for Python v3.7.
Commits:
- `poetry.lock`: Update `isort` (5.11.4 -> 5.11.5)
- `pyproject.toml`: Don't upgrade `isort` to 5.12.0
=> Update isort to v5.11.5, but no further

fawltydeps/main.py, noxfile.py, tests/sample_projects/empty/expected.toml, tests/sample_projects/mixed_project/expected.toml, tests/sample_projects/mixed_project/main.py, tests/sample_projects/mixed_project/pyproject.toml, tests/sample_projects/mixed_project/subdir1/notebook.ipynb, tests/sample_projects/mixed_project/subdir1/script.py, tests/sample_projects/mixed_project/subdir1/setup.cfg, tests/sample_projects/mixed_project/subdir2/notebook.ipynb, tests/sample_projects/mixed_project/subdir2/script.py, tests/sample_projects/mixed_project/subdir2/setup.py, tests/test_analysis.py, tests/test_cmdline_options.py, tests/test_extract_imports_simple.py
While working on the project traversal refactoring that I talked about yesterday,
these commits that do not strictly need to be part of that work has settled down
to the bottom of my branch. They deserve to be reviewed/considered separately before
the rest of the (still-ongoing) traversal work is submitted.
Commits:
- `test_extract_imports_simple`: Minor inconsequential fixes
- `sample_projects`: Add empty project
- `sample_projects`: Add mixed project
- `main`: Refactor `Analysis` object to remove annoying asserts
=> Preparing for the traversal refactoring

fawltydeps/main.py, tests/test_cmdline.py, tests/utils.py
Tests refactor aiming at speeding up the tests and reducing some unnecessarily tested logs equalities, that may end up slowing down refactors of the code.
Things improved:
- fixed bug in `print_output` function, where one of the writers were still using `sys.stdout`.
- introduce `ProjectTestsVector` and parameterized some of the tests in `tests_cmdline`
- introduce `run_fawltydeps_function` that uses `main` function instead of subprocesses to run FawltyDeps. Tests with using this function are simpler, we do not collect `stderr` and only compare output and exit code.
- rewrite some of tests in `test_cmdine` to use the above function to reduce unnecessary checks of log messages,
From a simple check below, we see that there is some improvement in the execution time of tests suites. There are …
=> Tests refactor: running fawltydeps on 'main' instead of in subprocess in command line tests

tests/test_cmdline.py, tests/test_cmdline_options.py, tests/utils.py
Following conversation with @jherland in https://github.com/tweag/FawltyDeps/pull/271#discussion_r1163887987 a name change of `run_fawltydeps` to `run_fawltydeps_subprocess` to follow the same naming convention as with `run_fawltydeps_function`.
The change is done separately from #271 for more atomic PRs.
=> Rename run_fawltydeps to run_fawltydeps_subprocess

README.md, fawltydeps/cli_parser.py, fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/settings.py, fawltydeps/types.py, tests/conftest.py, tests/test_cmdline.py, tests/test_configured_run.py, tests/test_packages.py, tests/test_settings.py
Follow-up on #287 .
In this PR an option to read the mapping directly from the configuration file (pyproject.toml). This is a useful option when we have only a few mapping entries we want to adjust.
What changed:
- in `Settings`, field `custom_mapping` was renamed to `custom_mapping_file` (and the related elements accordingly). This field keeps a path to mapping file
- in `Settings` a new field `custom_mapping` was added, which is a dictionary of packages and list of modules they export.
- `UserDefinedMapping` is using now both, the file and the custom mapping in form of a dictionary. If both the mapping from file, and the custom mapping contain the same key (package), the mapping from pyproject.toml is taken. This is because  pyproject.toml is usually better maintained, with smaller …
=> User-defined mapping: add option to read mapping from configuration file

fawltydeps/extract_declared_dependencies.py, fawltydeps/extract_imports.py, fawltydeps/main.py, fawltydeps/settings.py, fawltydeps/traverse_project.py, fawltydeps/types.py, noxfile.py, tests/sample_projects/no_issues/.venv/lib/python3.10/site-packages/dummy_package/code.py, tests/sample_projects/no_issues/.venv/lib/python3.10/site-packages/dummy_package/setup.py, tests/test_cmdline.py, tests/test_deps_parser_determination.py, tests/test_extract_declared_dependencies_errors.py, tests/test_extract_declared_dependencies_success.py, tests/test_extract_imports_errors.py, tests/test_extract_imports_simple.py, tests/test_traverse_project.py
This is the first part of several with the ultimate goal to:
- Support ignore patterns to skip various parts of a project's directory structure (#226).
- Supporting multiple --pyenv options (#249).
- Allowing auto-discovery of venvs within the project dirs (also issue 249).
- Have the discovery of such venvs ignore code/deps otherwise found inside those venvs (barely mentioned in a footnote to issue 249).
- Adding actions to list code sources and deps sources (`--list-code-sources` and `--list-deps-sources`, not yet tracked in any issue, I believe)
**This part** of the bigger refactoring, however, does not do any of that.
There should in fact be ~zero observable difference before and after this PR (modulo some changed INFO log messages). This PR is all about providing a single traversal …
=> Traverse refactor, part 1

fawltydeps/__main__.py, fawltydeps/cli_parser.py, tests/test_invocation.py
It is common for Python packages that offer a command-line interface to
expose this via the `__main__` module in the package. See [1] for info.
Also add some tests to verify the various ways we can now invoke the
fawltydeps command-line interface:
- using the `fawltydeps` entry point
- calling the `fawltydeps.main.main()` function from inside Python
- running `python -m fawltydeps`
These tests discovered that the program name shown at the start of the
`--help` message did not make sense when using the latter two invocations.
Fix that by explicitly passing the program name to `argparse`.
Fixes: https://github.com/tweag/FawltyDeps/issues/309
Suggested-by: Timothée Mazzucotelli <pawamoy@pm.me>
[1]: https://docs.python.org/3/library/__main__.html#main-py-in-python-packages
=> Add fawltydeps.__main__ module to allow 'python -m fawltydeps'

fawltydeps/settings.py, tests/test_cmdline.py
Fixes #265:
- TOML's booleans (true/false) are slightly different to Python's (True/False).
- The way to pass None from TOML is to not set the corresponding config directive.
This was needed to let new tests pass in #298.
=> Fix boolean representation and skip null values in generated toml config

fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/types.py, tests/test_packages.py
Prerequisite for #266 . Related to #299.
As discussed in a few team meetings, we decided on an option that if no mapping is found for a dependency (for example because identity mapping is disabled and we did not found everything in the environment) then we report it as an error.
In this PR I introduce:
- `UnresolvedDependenciesError` to be raised when all resolvers have finished and there are still unresolved dependencies in the pool
- exit code 5 for cases where not all dependencies have been maped
- dummy test to be filled when we allow for a case with no fallback to identity mapping (I tested by commenting out adding identity mapping to the resolvers stack). Follow-up PR will introduce `--install-deps` as a cli option, and the `resolve_dependencies` logic will be changed then. 
This PR …
=> Fail execution if not all dependencies are resolved.

fawltydeps/packages.py, poetry.lock, pyproject.toml, tests/test_invocation.py, tests/utils.py
(Depends on #313)
Commits:
- `tests.utils.assert_unordered_equivalence()`: More details when it fails
- `test_invocation`: Fix `pytest.skip()` message
- `pyproject.toml`: Pin `importlib_metadata` to latest release ==v6.6.0
=> Pin our importlib_metadata version (and some cosmetic fixes)

fawltydeps/packages.py, noxfile.py, tests/test_install_deps.py, tests/test_local_env.py
Until now, we have not handled the `CalledProcessError` that is raised when `pip install` fails to install the given requirements in `TemporaryPipInstallResolver.temp_installed_requirements()`.
This commit adds two new flags to `.temp_installed_requirements()`:
- `ignore_errors`: This disables the `CalledProcessError` and logs a warning message instead.
- `retry_each`: In combination with the above, when `pip install` fails, this will retry `pip install` on each individual requirement in order. The effect of this will be to install the subset of the given requirements that we _can_ install, leaving only the problematic requirements uninstalled.
Using both of these flags enables `TemporaryPipInstallResolver` to do a "best effort" installation of dependencies: Inside the …
=> `TemporaryPipInstallResolver`: Handle `pip install` errors gracefully

README.md, fawltydeps/cli_parser.py, fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/settings.py, tests/test_cmdline.py, tests/test_install_deps.py, tests/test_local_env.py, tests/test_real_projects.py, tests/test_resolver.py, tests/test_sample_projects.py, tests/test_settings.py
These are the commits that were originally part of #313, but now split into this PR.
Commits:
- `LocalPackageResolver`: Accept multiple pyenvs
- Add support for multiple `--pyenv` options
- `settings.print_toml_config()`: Represent sets as sorted lists
=> Support multiple `--pyenv` options

fawltydeps/packages.py, tests/test_local_env.py
Until now, the `--pyenv` option has accepted any path that points inside a Python environment, e.g.:
- `.venv/`
- `.venv/bin`
- `.venv/bin/python`
- `.venv/lib`
- `.venv/lib/python3.11`
- `.venv/lib/python3.11/site-packages`
These all unambiguously point to the Python environment rooted at `.venv/`, and they will all result in `LocalPackageResolver` looking for packages inside `.venv/lib/python3.11/site-packages`.
But this is all assuming that `.venv/lib/python3.11/site-packages` is the _only_ directory inside that Python environment that can hold Python packages.
We could have a situation where there are _multiple_ `site-packages` dirs inside `.venv/`:
- `.venv/lib/python3.9/site-packages`
- `.venv/lib/python3.11/site-packages`
In this case[^1], things start to go off the rails. Before …
=> `LocalPackageResolver`: Handle multiple package dirs inside one Python env

tests/sample_projects/pyenv_galore/.venv/lib/python3.10/site-packages/dummy_package/code.py, tests/sample_projects/pyenv_galore/.venv/lib/python3.10/site-packages/dummy_package/setup.py, tests/sample_projects/pyenv_galore/__pypackages__/3.10/lib/a_module.py, tests/sample_projects/pyenv_galore/__pypackages__/3.7/lib/a_package/__init__.py, tests/sample_projects/pyenv_galore/another-venv/lib/python3.11/site-packages/another_module.py, tests/sample_projects/pyenv_galore/another-venv/lib/python3.11/site-packages/setup.py, tests/sample_projects/pyenv_galore/another-venv/lib/python3.8/site-packages/another_package/__init__.py, tests/sample_projects/pyenv_galore/expected.toml, tests/sample_projects/pyenv_galore/poetry2nix_result/lib/python3.9/site-packages/some_module.py, tests/test_sample_projects.py, tests/test_traverse_project.py
(Depends on #324)
There are more preparatory steps on the way to integrating Python environments logic into the `traverse_project` module.
Commits:
- `test_sample_projects`: Accept new 'pyenvs' directive in `expected.toml`
- `sample_projects`: Add `pyenv_galore` 'project'
- `test_traverse_project`: Fix incorrect `.project` member for a test vector
- `test_traverse_project`: Prepare for testing with 'pyenvs'
=> Prepare test suite for traversing Python environments

poetry.lock, pyproject.toml
=> Allow isort >= 5.12 when running on Python > 3.7

pyproject.toml
According to [wiki](https://en.wikipedia.org/wiki/Software_release_life_cycle)'s description pf stages of development . 
> The alpha phase usually ends with a [feature freeze](https://en.wikipedia.org/wiki/Freeze_(software_engineering)), indicating that no more features will be added to the software.
Before reaching the mapping milestone we will not be feature complete. In fact I am not sure open source software ever is feature complete. 
FawltyDeps fulfills other criteria for alpha version:
> In general, an alpha version or release of a software package intends to do something particular, mostly does so, yet is not guaranteed to do so fully.
In fact, when mapping milestone is complete we will fall into beta stage:
> A beta phase generally begins when the software is feature complete but …
=> Change development status to 3- Alpha

README.md, fawltydeps/cli_parser.py, fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/traverse_project.py, fawltydeps/types.py, tests/sample_projects/pyenv_galore/expected.toml, tests/test_traverse_project.py
(Depends on #325)
This is at the heart of solving #249, and IMHO one of the major pieces remaining in the Mapping Strategy milestone.
With this, FawltyDeps is able to:
- automatically find Python environments inside the project directory (`basepath`)
- automatically _disregard_ files inside the Python environment for `.code` and `.deps`
Commits:
- `traverse_project`: Add support for finding/validating Python environments
- `main`: Use `PyEnvSource` objects when resolving dependencies
- Update documentation related to Python environments
=> Teach FawltyDeps to automatically discover Python environments inside the project

fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/types.py, tests/test_install_deps.py, tests/test_local_env.py, tests/test_packages.py, tests/test_real_projects.py, tests/test_resolver.py
(Depends on #326)
Commits:
- `test_resolver`: Simplify `generate_expected_resolved_deps()` helper
- `packages`: Split `setup_resolvers()` out of `resolve_dependencies()`
- `LocalPackageResolver`: Construct from `PyEnvSource` objects
- `package`: Always normalize `Package.package_name`
=> Various cleanups after integrating Python environments into `traverse_project`

tests/conftest.py, tests/test_cmdline.py, tests/test_configured_run.py, tests/test_extract_declared_dependencies_success.py
While planning the addition of a new `--list-source` command-line options, I found a need for a more general fixture to create a temporary Python project with imports, declared deps, as well as Python environments.
This PR introduces that fixture, and replaces a handful of less general fixtures with the new one.
Commits:
- `fake_venv`: Allow customization of venv location and Python version
- `conftest`: Add a generalized `fake_project()` fixture
- `tests`: Replace only use of `project_with_requirements()`
- `tests`: Replace only use of `project_with_setup_pyproject_and_requirements`
- `tests`: Replace only use of `project_with_pyproject()`
- `tests`: Replace only use of `project_with_setup_cfg()`
- `tests`: Replace `project_with_code_and_requirements_txt` with `fake_project`
=> Test refactoring: fake_project fixture

README.md, fawltydeps/settings.py, tests/test_cmdline.py
Update the order of options in the Configuration section of the documentation. to be the same as the message from the CLI.
Move 'custom_mapping_file' Settings entry to the bottom, to be closer to the custom mapping section in the generated TOML.
=> Documentation polishes:  Update the order of options in the Configuration section of the documentation.

fawltydeps/packages.py, fawltydeps/settings.py, tests/test_cmdline.py, tests/test_settings.py
This is a rather embarrasing omission from PR #326 (Teach FawltyDeps to automatically discover Python environments inside the project):
Although that PR did include code to traverse within a given `--pyenv` path to find Python environments, the PR "forgot" to actually switch the _default_ behavior of `--pyenv`:
The default value of `settings.pyenvs` remained an empty set, and there were no changes to have `basepath` influence the value of `settings.pyenvs`.
This PR fixes that:
- When neither `--pyenv` nor `basepath` is given, `settings.pyenvs` should default to the current directory.
- When `--pyenv` is not given, but `basepath` is given, `basepath` should override the default `settings.pyenvs`.
- When `--pyenv` is given, it overrides `basepath`.
In short `settings.pyenvs` should behave …
=> Fix Settings.pyenvs to _actually_ use basepath by default

README.md, fawltydeps/cli_parser.py, tests/test_cmdline.py, tests/test_cmdline_options.py, tests/test_settings.py
In this PR, `--install-deps` option is exposet to the user. It is almost the last piece of puzzle to add installing dependencies in a temporal virtual environment as a dependenceny mapping resolver.
We are left with describing it in the documentation #282 .
I tested the `--install-deps` option in CLi and if the virtual environment contains a dependency it is not installed in the temporal environment 👍
=> ADD CLI option for --install-deps

.github/workflows/tests.yaml, noxfile.py, poetry.lock, pyproject.toml
Closed #123 
This PR adds a functionality of running fawltydeps against itself in the GitHub Actions CI.
While running fawltydeps, it reads in the python environment from `~/.cache/pypoetry/virtualenvs` and ignores format related dependencies (`black`, `codespell`, `colorama`, `hypothesis`, `mypy`, `nox`, `pylint`, `pytest`, and `types-setuptools`).
Also, this PR declares `setuptools` as a dependency since `pkg_resources` has been imported to the main code.
=> Run fawltydeps against itself in CI

fawltydeps/packages.py, tests/test_install_deps.py, tests/test_packages.py
This PR constitutes the last missing piece of the mapping puzzle.
Identity mapping is suppressed if and only if install-deps is chosen.
Prior to this PR, any dependencies unresolved by `pip install` were passed to identity mapping. It was practically impossible to have any unresolved dependencies and therefore to have the `UnresolvedDependencyError` raised. This error is now raised in the only case where the `TemporaryPipResolver` fails to install a given dependency. In all other cases, identity mapping still resolves any dependencies left unresolved by prior resolvers in the stack.
Closes #299
=> Make identity mapping and install-deps mutually exclusive

README.md, fawltydeps/cli_parser.py, fawltydeps/main.py, fawltydeps/settings.py, fawltydeps/types.py, tests/test_cmdline.py
Make the traversal logic in FawltyDeps more visible/debuggable to the end user:
- Add the `*Source` objects to the JSON output
- Add the `--list-sources` CLI action with a human-readable version of the same
---
Commits:
- `main`: Add `Analysis.sources` to JSON output
- Add `--list-sources` CLI argument
- `main`: Reformat `print_human_readable()` to fix pylint's 'Too many branches'
=> Add `--list-sources` to CLI

.github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/tests.yaml
=> Pin version of Poetry in CI to 1.5.1 to maintain support for Python 3.7

fawltydeps/packages.py
I noticed this while playing around with `--install-deps` and `--json`, and
at the same time piping the JSON output into `jq` for filtering/colors:
The `pip install` that is triggered by `--install-deps` will print status
messages to both stdout and stderr, and since these are not handled by
our `subprocess.run()` call, they will appear directly on _our_
stdout/stderr. When piping our stdout to `jq` this causes `jq` to get
those status messages (preceding the JSON output) on its stdin, and it
predictably aborts with an error message.
This commit fixes the issue in two ways:
First, we pass `--quiet` and `--disable-pip-version-check` to `pip install`,
to silence some common/unnecesary output. This seems sufficient to make
`pip install` silent when everything works as expected. However, when …
=> TemporaryPipInstallResolver: Prevent `pip install` from polluting stdout

fawltydeps/extract_declared_dependencies.py, tests/test_deps_parser_determination.py
Zhihan found that the plotly project has some requirements files that
are not recognized by FawltyDeps, with names like `requirements_abc.txt`.
Using the underscore as a separator in the filename does not match our
regex, which requires a word boundary (`"\b"`) around the `"requirements"`
string in the filename.
Fix our regex: There is no reason why the underscore separator should
disqualify this as a requirements file, and simplifying the regex to
`".*requirements.*\.(txt|in)"` is unlikely to introduce false positives
(files that should _not_ be recognized as `requirements.txt` files, but
now are).
Also add unit tests precisely for parsing filenames of dependency files
as I could not find another test case that tested exactly this.
=> Relax regex re. recognizing requirements.txt

fawltydeps/extract_declared_dependencies.py, fawltydeps/extract_imports.py, fawltydeps/main.py, tests/conftest.py, tests/sample_projects/legacy_encoding/big5.py, tests/sample_projects/legacy_encoding/expected.toml, tests/test_cmdline.py, tests/test_extract_declared_dependencies_success.py, tests/test_extract_imports_simple.py, tests/utils.py
As #374 demonstrates, FawltyDeps does not interpret/follow encoding declarations in Python source code.
These encoding declarations have been part of Python for a long time, first introduced in [PEP 263](https://peps.python.org/pep-0263/), and currently documented here: https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations
As far as I can see, these encoding declarations do not really apply to Jupyter notebooks, for the simple reason that notebooks are stored in JSON files, and JSON is specified to always be UTF-8 encdoded. Still we need to support these in three cases:
- for Python source files passed to `extract_imports.parse_python_file()`,
- for Python source code passed directly on FawltyDeps' stdin,
- for `setup.py` files parsed by …
=> Handle Python code with embedded encoding declarations

README.md, fawltydeps/cli_parser.py, fawltydeps/main.py, fawltydeps/packages.py, noxfile.py, tests/test_cmdline.py, tests/test_local_env.py, tests/test_packages.py, tests/test_resolver.py, tests/utils.py
Fixes #392.
We foresee no harm or significant cost by simply using the current Python environment as a separate step in FawltyDeps' resolver stack.
The step is introduced _after_ any other local environments (found inside the project), but before we either fall back to then expensive `TemporaryPipInstallResolver`, or the suboptimal `IdentityMapping`.
As explained in the third commit message, this is somewhat of a return to our roots:
> In fact, this is partially a return to our pre v0.7 behavior where we would always (then: only) find packages in `sys.path`. Since v0.7 we allowed `--pyenv` to override this, and since v0.12, we also started searching for pyenvs under `--pyenv` or `basepaths` given on the command line. The result of this is that by now, the current environment is only …
=> Reintroduce current Python environment as a separate level in our resolver stack

.pre-commit-hooks.yaml, README.md
The `check-undeclared` hook runs only on files being committed.
Fixes: GH-385
With https://github.com/msabramo/fawltydeps-demo1/blob/GH-385-fix-my-fork/.pre-commit-config.yaml, I get this output:
```
$ cat .pre-commit-config.yaml
repos:
- repo: https://github.com/msabramo/FawltyDeps
rev: 4bca742
hooks:
- id: check-undeclared
args:
- --detailed
- --code     # --code always has to be last argument, because it must precede list of files
- id: check-unused
args:
- --detailed
$ cat main.py
import requests
import pandas
$ cat another.py
import sqlite
$ cat requirements.txt
requests
pyramid
$ git status
On branch GH-385-fix-my-fork
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
new file:   main.py
Untracked files:
(use "git add <file>..." to include in what will be …
```
=> Separate `check-undeclared`, `check-unused` pre-commit hooks

fawltydeps/dir_traversal.py, fawltydeps/traverse_project.py, fawltydeps/utils.py, tests/test_dir_traversal.py, tests/utils.py
Preliminary changes to clean up the code in preparation for work on supporting gitignore-style patterns for ignoring parts of the project during traversal.
Commits:
- `tests/utils.py`: Better output when `assert_unordered_equivalence` fails
- `DirectoryTraversal`: Allow attaching multiple data items in `.add()`
- Move `DirectoryTraversal` into its own module
- `dir_traversal`: Rename `.ignore()` to `.skip_dir()`
- `dir_traversal`: Refactor data on each traversal step into its own class
- `test_dir_traversal`: Make use of `ExpectedTraverseStep` self-documenting
=> Preliminary refactoring before `--ignore` feature

PyPI_analysis/main.py
In this PR, we modified the current code of identifying main code directories by the following points:
- return all directories that contains python code files (`.py` or `.ipynb`) instead of the maximum one
- in case that there are multiple packages/modules in one repository
- exclude all files that contains `test` rather than starts with it
- adjust summary/detailed/json outputs rendering
=> PyPI Analysis: identify main code directories 

README.md
We have a new [Discord channel ](https://discord.com/channels/1174731094726295632/1176462512212951090):tada: 
This PR adds:
-  a shield with an invitation link 
-  information  in README with invitation link and the FawltyDeps channel link
=> Add Discord channel references

.github/workflows/format.yaml, .github/workflows/lint.yaml, .github/workflows/self_test.yaml, .github/workflows/tests.yaml, fawltydeps/extract_declared_dependencies.py, fawltydeps/packages.py, fawltydeps/types.py, fawltydeps/utils.py, pyproject.toml, tests/conftest.py, tests/project_helpers.py, tests/real_projects/python-algorithms.toml, tests/test_cmdline.py, tests/test_cmdline_options.py, tests/test_deps_parser_determination.py, tests/test_dir_traversal.py, tests/test_local_env.py, tests/test_real_projects.py, tests/test_resolver.py, tests/test_sample_projects.py, tests/test_settings.py, tests/test_traverse_project.py, tests/test_types.py, tests/utils.py
To support MacOS it is enough to add `macos-latest` to the test matrix and allow for longer runs for tests that use `--install-deps` option. 
To support Windows we needed to:
- change all paths to be system-agnostic (5843d1efced695bf374b82fe3f385a1bdb97a8f4)
- change paths that referred to python executable, pip executable and site packages to work on all systems (36e957a174ff5bd68fc48dcefac43447380bdbe9, 8c4ecb984d9bf5ebe6d57991aee1f2bc4f76714e, d68917162b5f58a49c678122f824f80c2755e43d)
- Adjust command line script that creates virtual environments for tests (73e1819a38b83a2e51728bf5832df53c8e047ffd)
- Skip irrelevant tests (442db9696631777e3c93f56823f27b9d4abf9525, 3b5e3b6870e5ee9d827bd9f5b00676d58452af37)
- skip real-project tests as the test setup does not work well with Windows and …
=> MacOS and Windows support

fawltydeps/utils.py, poetry.lock, pyproject.toml, tests/test_traverse_project.py
Fixes #408.
Use `>=` instead of `^` in pyproject.toml to not be too restrictive as
to which version of our dependencies is acceptable when a user installs
FawltyDeps into their project's venv.
The `^` specifier allows for "SemVer compatible" updates to the specified
version, but the exact rules around these are complex, and - it seems -
more restrictive than what we want (at least for most of our deps.
The new `>=` will allow for _any_ newer version of a dependency to be
used. We will need to be somewhat careful (and frequent) in checking that
a new version a dependency does not break the APIs we are using.
See https://python-poetry.org/docs/dependency-specification/ for more
details about the different available specifiers.
To verify that upgraded dependencies do not break FawltyDeps, we …
=> Loosen version constraint on core dependencies and re-pin lock file

README.md, fawltydeps/cli_parser.py, fawltydeps/dir_traversal.py, fawltydeps/main.py, fawltydeps/settings.py, fawltydeps/traverse_project.py, noxfile.py, poetry.lock, pyproject.toml, tests/sample_projects/hidden_files/.hidden.code.py, tests/sample_projects/hidden_files/.hidden.requirements.txt, tests/sample_projects/hidden_files/.hidden_dir/code.py, tests/sample_projects/hidden_files/.hidden_dir/requirements.txt, tests/sample_projects/hidden_files/.venvs/.venv/lib/python3.10/site-packages/dummy_package/code.py, tests/sample_projects/hidden_files/.venvs/.venv/lib/python3.10/site-packages/dummy_package/setup.py, tests/sample_projects/hidden_files/.venvs/another-venv/lib/python3.11/site-packages/another_module.py, tests/sample_projects/hidden_files/.venvs/another-venv/lib/python3.11/site-packages/setup.py, tests/sample_projects/hidden_files/.venvs/another-venv/lib/python3.8/site-packages/another_package/__init__.py, tests/sample_projects/hidden_files/expected.toml, tests/test_cmdline.py, tests/test_dir_traversal.py, tests/test_sample_projects.py, tests/test_settings.py, tests/test_traverse_project.py
Support gitignore-style patterns given directly in the configuration or on the command line. No support for indirectly reading ignore patterns from files, yet.
See #391 for a follow-up PR that vendors/integrates the `gitignore_parser` dependency instead of depending on it, as we cannot really use its "public" API as intended.
Commits:
- `test_dir_traversal`: Add `.skip_me` member to each `DirectoryTraversalVector`
- Add `gitignore_parser` as a new dependency
- `DirectoryTraversal`: Initial support for exclude patterns
- `dir_traversal`: Add `excluded_*` fields to `TraversalStep`
- `dir_traversal`: Do not exclude an explicitly `.add()`ed path
- `traverse_project`: Use new `exclude` feature to exclude "hidden" paths
- `Settings`: Add `.exclude`, paths to exclude during project traversal
- …
=> Support exclude patterns

LICENSE, fawltydeps/dir_traversal.py, fawltydeps/gitignore_parser.py, fawltydeps/main.py, poetry.lock, pyproject.toml, tests/test_cmdline.py, tests/test_dir_traversal.py, tests/test_gitignore_parser.py, tests/test_traverse_project.py
For once, I'm _not_ going to suggest reviewing this on a commit-by-commit basis, as there are a lot of small commits here mainly to reassure myself that I'm not breaking anything along the way.
Looking at the total diff will give a better view of the net changes introduced here. Most of the added code is of course the `gitignore_parser` itself and its existing test suite. Both are rewritten fairly heavily in order to fit better into our style.
Still, I feel reasonably safe about these changes given the amount of test coverage we have in total now.
=> Integrate gitignore_parser into FawltyDeps

fawltydeps/dir_traversal.py, fawltydeps/gitignore_parser.py, fawltydeps/traverse_project.py, tests/conftest.py, tests/project_helpers.py, tests/real_projects/fawltydeps.toml, tests/test_cmdline.py, tests/test_dir_traversal.py, tests/test_gitignore_parser.py, tests/test_real_projects.py, tests/test_traverse_project.py
Thanks to Maria for actually _testing_ the new `--exclude` option from a user's POV, and notifying me of various griveous issues found. Here we try to tackle the ones that were found and raise in the later stages of #388:
- Running `fawltydeps` with `--exclude` and passing relative paths instead of absolute (our test suite relies too heavily on absolute paths)
- Passing "anchored" exclude patterns to `--exclude` was initially unsupported. Fix that.
- Give the user a warning when the `--exclude` option directly overlaps with a given path (in which case the given path will always win).
- Fix issues where the precedence between `--exclude` patterns and given paths were not followed in practice.
=> Fixes for various `--exclude` usability issues

fawltydeps/main.py, fawltydeps/settings.py, fawltydeps/types.py, tests/project_helpers.py, tests/test_real_projects.py, tests/test_sample_projects.py
`from __future__ import annotations` became available in Python 3.7, so there is no reason for us not to use it instead of the older "stringified" type annotations (for types that are not yet declared at the time the parser encounters the annotation).
=> Use __future__.annotations instead of stringified type annotations

tests/real_projects/python-algorithms.toml
qiskit v1.0 starts to declare the `qiskit` import name (see issue #176 for
details about the weirdness that precedes v1.0). This changes the
behavior of our `real_projects` test of the Algortihms project.
qiskit has also dropped support for Python 3.7 (since v0.44), hence it
is easier for us to keep our tests (which need to work with Python 3.7)
running on the older version, for now.
=> real_projects/python-algorithms: Pin qiskit at <1.0

.github/workflows/format.yaml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/tests.yaml, noxfile.py, shell.nix
This is in preparation for adding the `ruff` linter to FawltyDeps.
Commits:
- `.github/workflows`: Add timeouts to GitHub CI actions
- `noxfile.py`: Remove unused variable
- `shell.nix`: Update to current nixos-unstable
- `shell.nix`: Add support for installing wheels with compiled binaries
- `noxfile.py`: On Nix, auto-patch binaries installed by Nox
=> Dev/test environment: Support Python dependencies with pre-built binaries on Nix

CONTRIBUTING.md, docs/CodeDesign.md, fawltydeps/extract_declared_dependencies.py, fawltydeps/gitignore_parser.py, fawltydeps/limited_eval.py, fawltydeps/main.py, fawltydeps/packages.py, fawltydeps/settings.py, fawltydeps/traverse_project.py, fawltydeps/types.py, noxfile.py, poetry.lock, pyproject.toml, tests/project_helpers.py, tests/test_deps_parser_determination.py, tests/test_settings.py, tests/test_types.py, tests/utils.py
Remove `pylint`, as it has now been fully replaced by `ruff`. The last PR in a series of 3.
Commits:
- Docs: Mention `ruff` instead of `pylint`
- `noxfile.py`: Remove `pylint` from `lint` session
- Remove `pylint` annotations from source code
- `pyproject.toml`: Remove `pylint` from our dependencies
=> Remove pylint

CONTRIBUTING.md, docs/CodeDesign.md, fawltydeps/settings.py, fawltydeps/traverse_project.py, noxfile.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/project_helpers.py, tests/test_analysis.py, tests/test_cmdline_options.py, tests/test_compare_imports_to_dependencies.py, tests/test_dir_traversal.py, tests/test_extract_declared_dependencies_pyproject_toml.py, tests/test_extract_declared_dependencies_success.py, tests/test_extract_imports_simple.py, tests/test_install_deps.py, tests/test_local_env.py, tests/test_real_projects.py, tests/test_sample_projects.py, tests/test_settings.py, tests/test_traverse_project.py
Ruff comes with a built-in formatter (`ruff format`) which serves as a drop-in replacement for `black`. The difference in the formatting are minuscule, and can be seen in the second commit in this PR.
Also remove `isort` as a formatting dependency, since `ruff check` already performs the same checks.
Commits:
- Use ruff's default `line-length`
- Formatting changes introduced by `ruff format .`
- `noxfile.py`: Run `ruff format` instead of `black`
- Remove `black` as a dependency
- Remove `isort` as a formatting dependency
- Update docs to mention `ruff` instead of `black` + `isort`
=> Use `ruff format` instead of `black`

fawltydeps/extract_declared_dependencies.py, tests/test_extract_declared_dependencies_success.py
As described in issue #429, the s3transfer package comes with setup.py
where the `extras_require` dictionary does not map to a list of strings
(extra requirements), but instead map to a string directly.
When s3transfer is installed with this extra (e.g. `pip install
s3transfer[crt]`), the setuptools machinery handles this variation
gracefully, i.e. it interprets the string as if it was a single-element
list containing the same string.
An experiment reveals that the same interpretation occurs if a string is
passed directly in the `install_requires` argument.
This commit teaches FawltyDeps to do the same.
Also, if parse_one_req() fails to parse a requirement string, catch that
exception (likely an `InvalidRequirement` or some other subclass of
ValueError), and convert it into a …
=> parse_setup_py: Handle string dependency when we expect list of strings

.github/workflows/tests.yaml, README.md, docs/DesignDoc.md, fawltydeps/cli_parser.py, fawltydeps/packages.py, noxfile.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/project_helpers.py, tests/real_projects/python-algorithms.toml, tests/test_install_deps.py, tests/test_resolver.py, tests/test_sample_projects.py
`uv` is much faster than `pip` for installing package (it is also faster then `python -m venv` for creating virtualenvs). This PR switches from `venv`/`pip` to `uv` in three separate parts of our project:
1. Instruct Nox to use `uv` instead of `pip` to manage the virtualenv associated with each Nox session (first commit).
2. Use `uv` instead of `venv`/`pip` (when available) to manage virtualenvs for our `sample_project` and `real_projects` tests (next three commits).
3. Use `uv` instead of `venv`/`pip` (when available) to create and populate the temporary virtualenv managed by the `--install-deps` option (next two commits).
The first two points above only concern our tests and has no effect on the FawltyDeps program itself. The last one changes the behavior of the `--install-deps` option …
=> Use uv instead of pip to manage virtualenvs

fawltydeps/extract_declared_dependencies.py, poetry.lock, pyproject.toml, tests/test_real_projects.py
Fixes issue #443.
Getting away from our use of `pkg_resources` turns out to be relatively easy:
The `packaging` package from the [Python Packaging Authority](https://github.com/pypa) is probably as close as we can get to an official and authoritative upstream for this kind of logic, and the `packaging.requirements.Requirement` class seems to encapsulate the equivalent logic the `pkg_resources.Requirement` class that we have used for this purpose until now.
At least, our test suite seems to pass with no further adjustments after this change. :-)
Note that this only concerns the parsing of _single_ requirement strings as they occur in `setup.py` and `pyproject.toml` files.
For parsing full `requirements.txt` files we still rely on [pip-requirements-parser](https://github.com/nexB/pip-require …
=> Replace pkg_resources dependency with packaging.requirement

README.md
=> Add link to FawltyDeps GItHub Action in FAQ

.github/workflows/format.yaml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/self_test.yaml, .github/workflows/tests.yaml
Quick PR of somewhat urgent fixes related to our CI setup, Python v3.8 support, or both:
- Fix GH Actions failing due to Poetry v2 dropping support for Python v3.8
- Upgrade GH Actions action/cache helper to a supported version
- Fix omission of Python 3.12 and 3.13 for the `self_test` check in CI
- Fix #472 by stating that isort must be <v6 when we're on Python 3.8
=> Fixes to CI and isort dependency

fawltydeps/extract_deps/pyproject_toml_parser.py, tests/test_extract_deps_pyproject.py
Fixes #467.
See https://peps.python.org/pep-0735/ for details.
Commits:
- GH actions: Don't use Poetry >=v2
- `pyproject_toml_parser`: Add support for PEP 735 dependency groups
=> Add support for PEP 735 dependency groups

poetry.lock, pyproject.toml
Poetry, since version 2, [supports the PEP 621 standardized project
declarations in pyproject.toml](https://python-poetry.org/docs/faq/#how-do-i-migrate-an-existing-poetry-project-using-toolspoetry-section-to-use-the-new-project-section-pep-621). Let's start using them!
Also add a link to the new documentatin website, so that this shows up
in the "Project links" section on our PyPI page. This fixes #477.
=> Upgrade project declarations in `pyproject.toml`

.github/workflows/actionlint.yaml, .github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/format.yaml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/self_test.yaml, .github/workflows/tests.yaml
As part of me learning [CodeQL](https://codeql.github.com/), I'm looking at how to run CodeQL Python security rules on FawltyDeps, in its CI. When doing so, I noticed that FawltyDeps' CI had no quality checks, so I'm proposing to add one.
* [actionlint](https://github.com/rhysd/actionlint) is a well-established checker
* There was only one bash error found by actionlint, which I fixed in commit `CI: fix shell warning found by actionlint`, well done team :clap: 
* There was a warning about the `checkout` action version being too old. I fixed it, I think it's not controversial
* There is a warning about the `setup-python` version being too old. I didn't fix it, as I think the changelog should be inspected to understand what updating means and this seemed outside the scope of this PR. So …
=> CI: call actionlint to check workflow files

fawltydeps/extract_imports.py, fawltydeps/utils.py, tests/test_extract_imports_simple.py
In #490 @layus demonstrated a bug introduced in PR #489: When `--base-dir` is used to point to a directory that is not a parent of the source file we're currently parsing, the `dirs_between()` helper enters an infinite recursion while attempting to trace out the intermediate directories between the source file and the base directory. Several things are wrong here, and all are fixed in this PR:
- `dirs_between()` does not have to be a recursive function, an iteration over `Path.parents` suffices.
- `dirs_between()` should detect when the given `parent` is NOT a parent dir of `child`, and raise a `ValueError` instead.
- When `parse_source()` calls `dirs_between()` to setup the `isort.Config` object for correctly determining 1st- vs 3rd-party imports, it must handle this case (by catching …
=> Fix infinite recursion when `--base-dir` is not a parent of a source file
